### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/webpack-serve#1]
## Misc Tasks

- [x] update koa-webpack
- [x] @webpack-contrib/webpack-hot-client
- [ ] webpack-serve-overlay
- [ ] webpack-serve-progress

## Expose API

- [x] ~~add~~ this was a dumb idea. middleware needs to be setup before `start` 
- [x] on

## New Features

- [x] add (custom middleware and ordering from config)
- [x] on (binding to events from config)

## Core Features

- [x] ~~after / before / setup~~ `add`
- [x] ~~clientLogLevel~~ (will be replaced by `logLevel`)
- [ ] ~~color - CLI only~~ --no-color - do we really need this?
- [x] ~~contentBase~~ `content`
- [x] `host`
- [x] ~~hot~~ --hmr
- [x] ~~hotOnly~~ --no-reload
- [x] https
- [x] ~~index~~ part of staticOptions add-on
- [x] ~~open / openPage~~ --open `<Boolean> | { app: <String>, path: <String> }`
- [x] `port`
- [x] ~~stdin - CLI only~~ --stdin-end-exit

## Provide for Pass-Through to webpack-dev-middleware

(Handled by the `dev` option)

- [x] headers 🔑
- [x] lazy 🔑 / filename 🔑
- [x] publicPath 🔑
- [x] watchOptions 🔑

## Add-Ons

These features shouldn't have been part of the webpack-dev-server core, but rather bolt-on, add-ons. We need examples of how to create the add-on functionality.

- [x] bonjour
- [x] compress
- [x] historyApiFallback
- [x] ~~inline (iframe status bar)~~ too complex, too little benefit
- [x] ~~overlay~~ see Misc Tasks
- [x] ~~progress - CLI only~~ see Misc Tasks
- [x] proxy
- [x] staticOptions
- [x] useLocalIp
- [ ] watchContentBase (chokidar) (on hold until `@webpack-contrib/webpack-hot-client` is created, as we need a way to tell the page to reload, and `webpack-hot-middleware` doesn't provide for that)
